### ISSUE TITLE
Version 0.1.9: Unable to find module "which"

### ISSUE THREAD

**Issue by nhunzaker** [karma-runner/karma-chrome-launcher#48]
I'm hitting the following issue when I upgrade to 0.1.9:

```shell
WARN [plugin]: Error during loading "[...]karma-chrome-launcher" plugin:
  Cannot find module 'which'
```

It looks like `which` is no longer in the package.json.

**Comment by nhunzaker** [comment]
It looks like https://github.com/karma-runner/karma-chrome-launcher/pull/47 addresses this

**Comment by wilsonjackson** [comment]
I can confirm this is fixed in 0.1.10. Thanks for the quick resolution dudez!
